# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0

# SETUP DONE !!!


---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false
# showDonateUrl:          https://kde.org/community/donations/

requirements:
    requiredStorage:    10 #GiB
    requiredRam:        1.0 #GiB
    internetCheckUrl:   http://example.com

    check:
        # - storage
        - ram
        - power
        - internet
        # - root
        - screen
    required:
        # - ram
        - internet
        - screen
geoip:
    style:    "none"
    url:      "https://geoip.kde.org/v1/ubiquity"  # extended XML format
    selector: "CountryCode"  # blank uses default, which is wrong
