# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configure one or more display managers (e.g. SDDM)
# with a "best effort" approach.
#
# This module also sets up autologin, if the feature is enabled in
# globalstorage (where it would come from the users page).
---
displaymanagers:
  - sddm

#If true, try to ensure that the user, group, /var directory etc. for the
#display manager are set up correctly. This is normally done by the distribution
#packages, and best left to them. Therefore, it is disabled by default.
basicSetup: false

sddm:
  configuration_file: "/etc/sddm.conf"
