# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0


# SETUP DONE !!!
# MODIFY THE INSTALLS

---
backend: pacman

skip_if_no_internet: false
update_db: true
ignore_update_db_error: false
update_system: false

pacman:
    num_retries: 2
    disable_download_timeout: false
    needed_only: false

operations:
  - install:
    - vi
    - vi-${LOCALE}
    - wget
    - binutils
  - remove:
    - vi
    - wget
    - binutils
