# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the one-user-system user module.


# SETUP DONE !!!


---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - lp
    - video
    - network
    - storage
    - name: wheel
      must_exist: false
      system: true
    - audio
    - name: nopasswdlogin
      must_exist: false
      system: true

sudoersGroup:    wheel

setRootPassword: true
doReusePassword: true

displayAutologin:   false
doAutologin:     false

passwordRequirements:
    minLength: 3
    maxLength: 64
    libpwquality:
        - minlen=8
        - maxrepeat=3
        - maxsequence=3
        - usersubstr=4
        - badwords=linux

allowWeakPasswords: true
allowWeakPasswordsDefault: false

user:
  shell: /bin/zsh
  forbidden_names: [ root ]
  home_permissions: "o700"
  nopasswd_group: "nopasswdlogin"

hostname:
  location: EtcFile
  writeHostsFile: true
  template: "n0ctos-${first}"
  forbidden_names: [ localhost ]

allowActiveDirectory: false #only [a-z][A-Z][-,_ etc...]

presets:
    fullName:
        # value: "OEM User"
        editable: true
    loginName:
        # value: "oem"
        editable: true
