# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#


# SETUP DONE !!!

# Options for EFI system partition.
efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    300MiB
    minimumSize:        32MiB
    label:              "EFI"

userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Up to 4GB
    - suspend   # At least main memory size
swapPartitionName:      swap
luksGeneration: luks1
allowZfsEncryption: false
drawNestedPartitions:   false
alwaysShowPartitionLabels: true
allowManualPartitioning:   true
initialPartitioningChoice: alongside
initialSwapChoice: small
defaultPartitionTableType: gpt
createHybridBootloaderLayout: false
defaultFileSystemType:  "ext4"
availableFileSystemTypes:  ["ext4","btrfs"]
directoryFilesystemRestrictions:
    - directory: "any"
      allowedFilesystemTypes: ["ext4","btrfs"]
    - directory: "/"
      allowedFilesystemTypes: ["ext4","btrfs"]
    - mountpoint: "efi"
      allowedFilesystemTypes: ["fat32"]
      onlyWhenMountpoint: true

# The ClearMounts job unmounts / unmaps things before partitioning.
# Some special entries under /dev/mapper are excepted from this process.
# The example lists the three hard-coded exceptions which always apply
# (they don't need to be listed here). Add other names or wildcards (with
# a trailing '*') to this list if the live-ISO has additional mounts.
essentialMounts: [ "live-*", "control", "ventoy" ]

lvm:
    enable: true